language: python
python:
<<<<<<< HEAD
  # - '3.6' # current default Python on Travis CI
  # - '3.7'
=======
  - '3.6' # current default Python on Travis CI
  - '3.7'
>>>>>>> 76cdcd2... fix python version
  - '3.8'

env:
  global:
    - DB_NAME=travis_ci_test
    - DB_USER=postgres
    - DB_HOST=localhost
    - DB_PORT='5432'
    - DB_PASSWORD=''
    - DB_PASS=''
    - SECRET_KEY=secret
    - DEBUG=True
    - ALLOWED_HOSTS=*
    - DB_ENGINE=django.db.backends.postgresql_psycopg2
    - LANGUAGE_CODE=en-us
    - LOG_LEVEL=DEBUG
    - TIME_ZONE=America/Sao_Paulo

install:
  - pip install -r requirements.txt
script:
  - python manage.py test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
