version: '3.1'

services:
  app:
    build: .
    restart: always
    image: diegogslomp/django-monitor
    env_file: .env
    volumes:
      - web_static:/usr/src/app/staticfiles
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    build: .
    restart: always
    image: diegogslomp/django-monitor
    env_file: .env
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    restart: always
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    restart: always
    build:
      context: ./nginx
    image: diegogslomp/nginx-proxy
    volumes:
      - web_static:/usr/src/app/static
    networks:
      - frontend
    ports:
      - "8000:80"
    depends_on:
      - app

  redis:
    restart: always
    image: redis:latest
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
