version: '3.1'

services:
  app:
    build: .
    restart: always
    image: monitor
    env_file: .env
    volumes:
      - web_static:/usr/src/app/static
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    build: .
    restart: always
    image: monitor
    env_file: .env
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    restart: always
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    restart: always
    build:
      context: ./nginx
    image: proxy
    volumes:
      - web_static:/usr/src/app/static
    networks:
      - frontend
    ports:
      - "8000:80"
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
