version: '3.1'

services:
  app:
    image: diegogslomp/django-monitor
    environment:
      SECRET_KEY: ')=^^v7e2e--*5swl77tij@w(t8z^v7j*^=s1na21#8e_&ymw%4'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      # All env below added until fix EOF in windows
      DEBUG: 'True'
      LOG_LEVEL: DEBUG
      ALLOWED_HOSTS: '*'
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      LANGUAGE_CODE: en-us
      TIME_ZONE: America/Sao_Paulo

    volumes:
      - static:/usr/src/app/static
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    image: diegogslomp/django-monitor
    command: python manage.py monitord
    environment:
      SECRET_KEY: ')=^^v7e2e--*5swl77tij@w(t8z^v7j*^=s1na21#8e_&ymw%4'
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      # All env below added until fix EOF in windows
      DEBUG: 'True'
      LOG_LEVEL: DEBUG
      ALLOWED_HOSTS: '*'
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
      LANGUAGE_CODE: en-us
      TIME_ZONE: America/Sao_Paulo
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  web:
    image: diegogslomp/nginx-proxy
    volumes:
      - static:/usr/src/app/static
    networks:
      - frontend
    ports:
      - '8000:80'
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  db:
  static:
