version: '3.1'

services:
  app:
    build: .
    image: monitor
    restart: always
    environment:
      DJANGO_LOG_LEVEL: DEBUG
      TELNET_USER: admin
      TELNET_PASS: secret
      DJANGO_SECRET_KEY: super_secret_key
    command: gunicorn -b 0.0.0.0:8000 main.wsgi
    networks:
      - frontend
      - backend
    depends_on:
      - migration

  monitord:
    build: .
    image: monitor
    restart: always
    environment:
      DJANGO_LOG_LEVEL: DEBUG
      TELNET_USER: admin
      TELNET_PASS: secret
      DJANGO_SECRET_KEY: super_secret_key
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  collectstatic:
    build: .
    image: monitor
    restart: on-failure
    environment:
      DJANGO_SECRET_KEY: super_secret_key
    command: python manage.py collectstatic --no-input
    volumes:
      - web_static:/usr/src/app/static

  migration:
    build: .
    image: monitor
    restart: on-failure
    environment:
      DJANGO_SECRET_KEY: super_secret_key
    command: python manage.py migrate
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    image: nginx
    restart: always
    volumes:
      - web_static:/usr/src/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - "8000:80"
    depends_on:
      - app
      - collectstatic

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
