version: '3.1'

services:
  app:
    build: .
    image: diegogslomp/django-monitor:dev
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DJANGO_SECRET_KEY: '283822994187305985740598263403493847rfdfbsldfiudfhgldsfzb'
      DJANGO_LOG_LEVEL: DEBUG
      DJANGO_DEBUG: "True"
      DB_PASSWORD: postgres
    command: gunicorn -b 0.0.0.0:8000 main.wsgi
    volumes:
      - web_static:/usr/src/app/static
      - ./misc/init.sh:/usr/src/app/init.sh
    ports:
      - 8000
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    image: diegogslomp/django-monitor:dev
    restart: always
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DJANGO_SECRET_KEY: '283822994187305985740598263403493847rfdfbsldfiudfhgldsfzb'
      DJANGO_LOG_LEVEL: DEBUG
      DJANGO_DEBUG: "True"
      DB_PASSWORD: postgres
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    image: nginx
    restart: always
    volumes:
      - web_static:/usr/src/app/static
      - ./misc/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - '8000:80'
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
