version: '3.1'

services:
  app:
    image: diegogslomp/django-monitor
    command: gunicorn -b 0.0.0.0:8000 main.wsgi
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - web_static:/usr/src/app/static
    ports:
      - 8000
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    image: diegogslomp/django-monitor
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    image: nginx
    restart: always
    volumes:
      - web_static:/usr/src/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - '9000:80'
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
