version: '3.1'

services:
  app:
    build: .
    image: django-monitor
    restart: always
    env_file: .env
    command: gunicorn -b 0.0.0.0:8000 main.wsgi
    volumes:
      - web_static:/usr/src/app/static
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    build: .
    image: django-monitor
    restart: always
    env_file: .env
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    image: nginx
    restart: always
    volumes:
      - web_static:/usr/src/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - "8000:80"
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
