version: '3.1'

services:
  app:
    image: diegogslomp/django-monitor
    restart: always
    environment:
      # Secret Key must be changed!
      DJANGO_SECRET_KEY: super_secret_key
      # DJANGO_LOG_LEVEL: INFO
      # DJANGO_DEBUG: False
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      PORT: 5432
      # LANGUAGE_CODE: en-us
      # TZ: UTC
      # Only used if there are ports registered
      # TELNET_USER: admin
      # TELNET_PASS: secret
    command: gunicorn -b 0.0.0.0:8000 main.wsgi
    volumes:
      - web_static:/usr/src/app/static
    networks:
      - frontend
      - backend
    depends_on:
      - db

  monitord:
    image: diegogslomp/django-monitor
    restart: always
    environment:
      # Secret Key must be changed!
      DJANGO_SECRET_KEY: super_secret_key
      # DJANGO_LOG_LEVEL: INFO
      # DJANGO_DEBUG: False
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      PORT: 5432
      # LANGUAGE_CODE: en-us
      # TZ: UTC
      # Only used if there are ports registered
      # TELNET_USER: admin
      # TELNET_PASS: secret
    command: python manage.py monitord
    networks:
      - backend
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    image: nginx
    restart: always
    volumes:
      - web_static:/usr/src/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - '8000:80'
    depends_on:
      - app

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  web_static:
